CREATE DATABASE CustomShop
GO
USE CustomShop
GO
CREATE TABLE Senarist
(
SenaristID INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(50),
Soyad NVARCHAR(50)
)
GO
CREATE TABLE Yonetmen
(
YonetmenID INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(50),
Soyad NVARCHAR(50)
)
GO
CREATE TABLE Film
(
FilmNo INT PRIMARY KEY NOT NULL,
Ad NVARCHAR(50),
Yili DATETIME,

)
CREATE TABLE Sirket
(
SirketID INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(100)
)
GO
CREATE TABLE CustomShop
(
FilmID INT PRIMARY KEY NOT NULL,
FilmNo INT FOREIGN KEY REFERENCES Film(FilmNo),
YonetmenID INT FOREIGN KEY REFERENCES Yonetmen(YonetmenID),
SenaristID INT FOREIGN KEY REFERENCES Senarist(SenaristID),
SirketID INT FOREIGN KEY REFERENCES Sirket(SirketID)
)

